### ISSUE TITLE
pip install powerdict fails

### ISSUE THREAD

**Issue by Jess-St** [OSUKED/Power-Station-Dictionary#18]
Both the pip install and install via setup_env.bat fail with the default requirements due to the requirements = pandas==1.1.5 numpy==1.19.4 in setup.ini which are not compatible with the latest python version 3.11 (nb: environment.yml only specifies python>=3.7). Workaround: the install succeeds with python version 3.9 or lower.

**Comment by AyrtonB** [comment]
Thank's for spotting this, I've juts pinned it to 3.9
